import { readable } from "svelte/store";

export const faqOptions = readable([
    [
        "Fragen zur Testung an der SPBS Singen", "z. B. Wie läuft die Testung ab?", "abc.com",
        [
            [ "Wie melde ich mein Kind zur Testung an?", 'Die Anmeldung erfolgt online am 09.-10.02.2022. Alle relevanten Informationen hierzu sowie ein Erklärvideo finden Sie <a href="./?article=anmeldung">hier</a>.' ],
            [ "Wann und wo findet die Testung statt?", 'Die Testung findet in der Schulpsychologischen Beratungsstelle in Singen (Julius-Bührer-Str. 4, 78224 Singen) im Zeitraum vom 21.02.-24.02.2022 statt, primär an den Wochentagen Montag und Dienstag.' ],
            [ "Welches Testverfahren wird verwendet? ", 'Ein standardisierter, normierter, schulnaher Begabungstest.<br>– Der Test dient dem Auswahlverfahren und stellt somit keine Individualdiagnostik dar (diese ist deutlich umfassender).<br>– Der Fokus liegt auf den kognitiven Fähigkeiten, diese werden im Test durch einen sprachlichen, einem mathematischen und figuralen Bereich abgefragt.<br> – Der Test wird als Gruppentestung durchgeführt (max. 12 Kinder).' ],
            [ "Welches Testergebnis muss mein Kind erreichen, um zum nächsten Schritt des Aufnahmeverfahrens zugelassen zu werden?", "Das Aufnahmeverfahren zum HBZ ist Baden-Württembergweit einheitlich geregelt. Ein Grenzwert von T-Wert ≥ 63 ist vorgegeben (entspricht etwa einem Prozentrang von 90) d. h. ihr Kind muss einen T-Wert von 63 oder größer erzielen, was einer überdurchschnittlichen kognitiven Begabung entspricht (siehe auch Frage zu Interpretation des Testergebnisses). Wenn Ihr Kind den Grenzwert erreicht, ist es für den nächsten Schritt im Aufnahmeverfahren zugelassen: Ein Aufnahmegespräch mit der Schulleitung und der HBZ-Koordination." ],
            [ "Wie ist das Testergebnis zu interpretieren? Was sagt das Testergebnis über mein Kind aus?" , 'Die Ergebnisse Ihres Kindes werden mit früher durchgeführten Testergebnissen anderer 4. Klässler*innen verglichen (repräsentative Normstichprobe). Die Ergebnisse werden in T-Werte umgerechnet. <br>T-Wert zwischen 40 und 60 = durchschnittlicher Bereich<br>T-Wert unter 40 = unterdurchschnittlicher Bereich<br>T-Wert von über 60 = überdurchschnittlichen Bereich<br>Von einer Hochbegabung spricht man ab einem T-Wert von 70 (IQ-Wert = 130). Für die Aufnahme in den HBZ ist ein T-Wert von ≥ 63 notwendig.<br>– Begabungstests sind Momentaufnahmen und können in einem gewissen Rahmen variieren z. B. durch die Tagesform. Zudem ist kein Test perfekt. Daher wird bei den Ergebnissen meist ein Bereich angegeben in dem das „wahre“ Testergebnis mit sehr hoher Wahrscheinlichkeit liegt.<br>– Es gibt viele verschiedene Einflussfaktoren für Schulerfolg. Kognitive Fähigkeiten/Begabung ist einer davon. Weitere sind z.B. Vorwissen, Motivation/Engagement, Lern- und Arbeitsstrategien, häusliches sowie schulisches Lernumfeld usw.. Kinder mit hoher Begabung haben ein hohes Potenzial für sehr gute schulische Leistungen, allerdings muss das Potential auch ausgeschöpft werden. Eine hohe Begabung alleine reicht nicht aus. '],
            [ "Warum gibt es drei Werte: PR, T-Wert und IQ-Wert?", "Das Testergebnis Ihres Kindes kann auf drei verschiedene Arten dargestellt werden, nämlich als Prozentrang (PR), T-Wert oder IQ-Wert. Alle drei Werte können ineinander umgerechnet werden und beschreiben das gleiche Ergebnis. Wie bei der Frage „Wie ist das Testergebnis zu interpretieren?“ erklärt wird, werden die Ergebnisse Ihres Kindes mit früher durchgeführten Testergebnissen anderer Viertklässler*innen verglichen. Die Darstellung der Testergebnisse kann in T-Werten (Mittelwert: 50; durchschnittlicher Bereich: 40-60) oder auch in IQ-Werten erfolgen (Mittelwert: 100; durchschnittlicher Bereich: 85-115).Ebenso kann man das Ergebnis als Prozentrang (PR) angeben. Dieser gibt an, wie viel Prozent der Vergleichsgruppe (andere Viertklässler*innen) in dem Test weniger oder genauso viele Punkte erzielt haben wie Ihr Kind. Der mögliche Wertebereich reicht von einem PR von 0 bis 100 (durchschnittlicher Bereich: 16-84). Ein PR von 70 bedeutet bspw., dass 70 % der Vergleichsgruppe weniger oder genauso viele Punkte erreicht haben. Nur 30 % haben mehr Punkte erreicht. Bei der Interpretation von PR muss man etwas vorsichtig sein. Eine genauere Erklärungen finden Sie <a href='https://www.hogrefe.com/at/thema/normwerte-in-leistungstests-prozentraenge-richtig-interpretieren'>hier</a>." ],
            [ "Mein Kind wurde schon an anderer Stelle getestet, reicht das aus?", '– Ja, falls die Testung durch einen Schulpsychologen oder Schulpsychologin an einer Schulpsychologischen Beratungsstelle (SPBS) in Baden-Württemberg sowie am Kompetenzzentrum des LGH Schwäbisch Gmünd durchgeführt worden ist und nicht älter als 2 Jahre ist.<br>– Je nachdem, falls die Testung von einer SPBS außerhalb von Baden-Württemberg oder im Ausland durchgeführt wurde. Diese Situation bedarf individuelle Absprache und Klärung. Bitte nehmen Sie im Vorfeld Kontakt mit SPBS Singen auf.<br>– Nein, falls die Testung an Sozialpädiatrischen Zentren (SPZ), in Kinderarztpraxen oder bei niedergelassenen Psychologischen Psychotherapeutinnen und Psychotherapeuten durchgeführt wurde, als auch wenn die Testergebnisse in Praxen bzw. Instituten erhoben wurden, die eigens Dienstleistungen im Bereich Hochbegabtendiagnostik anbieten.' ],
            [ "Was ist Intelligenz?", 'Hier ist sich leider auch die Fachwelt nicht ganz einig, es gibt bis heute keine einheitliche Definition. Ein renommierter Wissenschaftler hat es folgendermaßen zusam-mengefasst:<br>»Intelligenz ist eine sehr allgemeine geistige Kapazität, die – unter anderem – die Fähigkeit zum schlussfolgernden Denken, zum Planen, zur Problemlösung, zum abstrakten Denken, zum Verständnis komplexer Ideen, zum schnellen Lernen und zum Lernen aus Erfahrung umfasst. Es ist nicht reines Bücherwissen, keine enge akademische Spezialbegabung, keine Testerfahrung. Vielmehr reflektiert Intelligenz ein breiteres und tieferes Vermögen, unsere Umwelt zu verstehen, zu kapieren, Sinn in den Dingen zu erkennen oder herauszubekomme, was zu tun ist.« <br>(Linda Gottfredson, 1997, S. 13, zitiert nach Rost, D. H. (2009).<br>(<a href="https://www.fachportal-hochbegabung.de/fragen/was-ist-intelligenz">https://www.fachportal-hochbegabung.de/fragen/was-ist-intelligenz</a>)' ],
            [ "Was versteht man unter intellektueller (Hoch-)Begabung?", 'Begabung bezeichnet ganz allgemein das leistungsbezogene Entwicklungspotenzial einer Person. Hochbegabung bezeichnet das überdurchschnittliche geistige Potenzial eines Menschen, welches sich unter günstigen Umweltbedingungen und gezielter Anregung zu herausragenden Leistungen oder großem Kenntnis- und Wissensreichtum entwickeln kann. Hochbegabung bezeichnet damit die Möglichkeit (nicht das Vorliegen) außergewöhnlicher Leistung.<br>(<a href="https://www.fachportal-hochbegabung.de/glossar/">https://www.fachportal-hochbegabung.de/glossar/</a>)' ],
            [ "Wie soll sich mein Kind auf den Test vorbereiten? ", 'Spezielle Vorbereitung ist nicht nötig. Im Test wird kein erlernter Schulstoff abge-fragt, sondern kognitive Fähigkeiten. Diese sind ungefähr (!) zur Hälfte durch Gene determiniert und zur anderen Hälfte durch die (jahrelange) Interaktion mit der Umwelt geprägt. Hilfreich ist, wenn die Familie gelassen mit der Testsituation umgeht und kein Druck ausgeübt wird. Es ist ganz normal, wenn Ihr Kind vor der Testung ein bisschen aufgeregt ist, das legt sich meist in Verlauf der ersten Minuten. Informieren Sie Ihr Kind gerne über den Ablauf der Testung (siehe Frage “ Wie läuft die Testung ab?“). ' ],
            [ "Was soll mein Kind zur Testung mitbringen?", '– einen Bleistift (weich) und Radiergummi<br>– etwas zu Essen und zum Trinken für die Pause<br>– eine Jacke / einen dickeren Pulli, da wir häufig lüften' ],
            [ "Wie läuft die Testung ab?", '– Ankunft und Begrüßung an der SPBS in Singen um 08:45 Uhr <br>– Wir sammeln die erforderlichen Unterlagen ein und vereinbaren die Termine für die Testergebnis-Rückmeldegespräche.<br>– Sie verabschieden sich von Ihren Kindern.<br>– Um 09.00 Uhr beginnt die Testung mit max. 12 Kindern in einem der großen Gruppenräume: Nach der Begrüßung und einer kurzen Vorstellungsrunde, erhalten die Kinder allgemeine Informationen zu der Testung. Vor jeder Aufgabe wird die Aufgabenstellung erklärt, es werden Beispiele zusammen bearbeitet und Fragen können gestellt werden. Aufgaben werden dann individuell schriftlich gelöst. Die Schüler*innen haben pro Aufgabe eine begrenzte Zeit zur Verfügung. Der Test besteht aus 3 Bereichen, zwischen den Bereichen machen wir jeweils eine Pause. Nach ca. 2,5 bis 3 Stunden ist die Testung beendet. <br>– Sie holen ihr Kind wieder an der SPBS ab.<br>Je nach Situation (z. B. Corona-Pandemie) kann sich der Ablauf etwas verändern.' ],
            [ "Wie geht es nach der Testung weiter? ", '– Am Nachmittag nach der Testung finden die Rückmeldegespräch statt (persönlich oder per Videokonferenz): Die Testergebnisse werden Ihnen mitgeteilt und erklärt. Auf Wunsch kann Ihr Kind auch gerne dabei sein.<br>– Im Anschluss bekommen Sie die Testergebnisse schriftlich zugesandt (Mail oder Post).<br>– Danach geben wir eine Liste mit den Namen der Schüler*innen, die den Grenzwert erreicht haben, an das Heinrich-Suso-Gymnasium weiter. Das Heinrich-Suso-Gymnasium von uns keine weiteren Informationen (Testergebnisse oder –profile werden nicht weitergegeben).<br>– Bei Erreichen des Grenzwerts folgt das Gespräch mit Schulleitung und HBZ-Koordination am Heinrich-Suso-Gymnasium. Bitte wenden Sie sich an die Schulleitung, um den nächsten Schritt des Aufnahmeverfahrens zu besprechen.<br>– Bei Nicht-Erreichen des Richtwerts: Sie müssen nichts weiter bezüglich des HBZ tun. Sie können sich für die Beschulung Ihres Kindes in einer Regelklasse am Heinrich-Suso-Gymnasium oder an einer anderen Schule entscheiden.' ],
            [ "Werden auf Besonderheiten meines Kindes (besonders jung, ADHS, geringe Deutschkenntnisse) eingegangen? ", 'Grundsätzlich ist uns wichtig, dass eine entspannte und störungsfreie Atmosphäre während der Testung herrscht, sodass alle Kinder gut und konzentriert arbeiten können. Fragen können jederzeit gestellt werden. Wenn es bei Ihrem Kind Besonderheiten gibt, die bei der Testung berücksichtigt werden sollten, nehmen Sie möglichst frühzeitig Kontakt mit uns auf.' ]
        ]
    ],
    [
        "Fragen zum HBZ am Suso", "z. B. Wird im HBZ ein anderer Stoff unterrichtet als in den Regelklassen?", "xyz.com",
        [
            [ "Wird im HBZ ein anderer Stoff unterrichtet als in den Regelklassen?", 'Es wird der Schulstoff gemäß Bildungsplan für allgemeinbildende Gymnasien unterrichtet. Dieser unterscheidet nicht zwischen HB- und Regelklassen. Es kann natürlich in Absprache mit der HB-Klasse zu Exkursionen oder Vertiefungen kommen, die über den Unterrichtsstoff hinaus gehen.' ],
            [ "Gibt es Unterschiede in der Benotung im HBZ im Vergleich zu den Regelklassen?", "Nein." ],
            [ "Worin unterscheidet sich der Unterricht im HBZ von dem in Regelklassen?", "Er ist grundsätzlich offener gehalten und öffnet sich vor allem in höheren Jahrgangsstufen. Dies ermöglicht u. a. Freiraum zum divergenten und kreativen Denken. Außerdem ist der HB-Unterricht vielfach projekt- bzw. handlungsorientiert angelegt. Die Unterrichtsgespräche sind bisweilen tiefgehend und haben interdisziplinären oder vernetzenden Charakter. Eine vertiefte Diskussion kann in der Breite stattfinden (und findet auch noch oft über den Unterricht hinaus statt)." ],
            [ "Gibt es ein Sammeltaxi, das die HBZ-Kinder z. B. aus dem Hegau abholen kann?", "Nein, leider nicht." ],
        ]
    ],
    [
        "Fragen allgemein zum Suso", "Diese FAQs werden derzeit von der Suso-Schulleitung erstellt.", "cdf.com",
        [

        ]
    ]
]);